#===========================================================
# Name: Klamath SRO RiverWare Post-Processing
# Author: D. Broman, USBR Technical Service Center
# Last Modified: 2018-08-02 by MMcGuire
# Description: Reads in RiverWare data files from the Klamath
# River Basin model and calculates performance measures.
#===========================================================
# User Inputs:

#- Working Directory
wd = 'C:/Projects/KlamathRiverBasin/PostProcess/'
#wd = 'C:/Users/MMcguire/Documents/GitHub/Klamath/PostProcess/'

#-Scenario Directory [Location of RiverWare data]
scenDir = 'C:/Projects/KlamathRiverBasin/RiverSmart/Scenario/'

#-Folder Header for Forecast Scenario Runs
scenHdr = 'MRM,RW,Rls,FcstInp'

#-Folder Header for Historical Runs
histHdr = 'MRM,RW,Rls,HistInp'
histDir = 'C:/Projects/KlamathRiverBasin/RiverSmart/Scenario/Historical/trace1'
# All models are run from Jan 1, with historical data appended from
# Jan 1 to start of forecast - forecast start times 1/1, 2/1, 3/1, 4/1, 5/1
#dateList = c('2006-01-01', '2010-01-01')

#- Output Directory
dirOup = 'data/output/'
dirEVS = 'C:/Projects/KlamathRiverBasin/EVS_5.6/Inputs/'

#===========================================================
#-postprocess_lib.r contains custom functions and required R packages
setwd(wd)
source('src/fncnLib.r')
dat_name_list = c('Run', 'Trace', 'RiverWareSlot', 'Time', 'Value', 'InputDMIName')

# List of Traces from 2006 Forecast Runs
trcTbl06 = fread('C:/Projects/KlamathRiverBasin/RiverSmart/Control/trcTbl.csv')
trcTbl06 = trcTbl06 %>% mutate(Set = '2006-01-01')

# List of Traces from 2010 Forecast Runs
trcTbl10 = fread('C:/Projects/KlamathRiverBasin/RiverSmart/Control/trcTbl2010.csv')
trcTbl10 = trcTbl10 %>% mutate(Set = '2010-01-01')

# Combine forecast trace tables
trcTbl = bind_rows(trcTbl06, trcTbl10)
trcTbl = trcTbl %>% mutate(InitDate = as.Date(InitDate))

# List of traces from 2006 historical runs
trcTbl06Hist = fread('C:/Projects/KlamathRiverBasin/RiverSmart/Control/trcTblHist.csv')

# List of tracers from 2010 historical runs
trcTbl06Hist = trcTbl06Hist %>% mutate(Set = '2006-01-01')

trcTbl10Hist = fread('C:/Projects/KlamathRiverBasin/RiverSmart/Control/trcTbl2010Hist.csv')
trcTbl10Hist = trcTbl10Hist %>% mutate(Set = '2010-01-01')

# Combine historical trace tables
trcTblHist = bind_rows(trcTbl06Hist, trcTbl10Hist)
trcTblHist = trcTblHist %>% mutate(InitDate = as.Date(InitDate))
#===========================================================
# Read in Data

ctDate = length(dateList)

datStrg = data.table()
datEWA = data.table()
datGage = data.table()
datIg = data.table()
datPjct = data.table()
datInfl = data.table()
datSply = data.table()
for(iterDate in 1:ctDate){
	dateSel  = dateList[iterDate]
	filePathTmp = paste0(scenDir, scenHdr, ',', dateSel, '/')

	# Storage
	strgTmp = read.rdf(paste0(filePathTmp, 'Storage.rdf'))
	datStrgTmp =  Rdf2dt(strgTmp)
	datStrgTmp = datStrgTmp %>% mutate(Set = dateSel)
	datStrg = datStrg %>% bind_rows(datStrgTmp)

	# EWA
	EWATmp = read.rdf(paste0(filePathTmp, 'EWA.rdf'))
	datEWATmp =  Rdf2dt(EWATmp)
	datEWATmp = datEWATmp %>% mutate(Set = dateSel)
	datEWA = datEWA %>% bind_rows(datEWATmp)

	#GaugeFlow
	gageTmp = read.rdf(paste0(filePathTmp, 'GageFlow.rdf'))
	datGageTmp =  Rdf2dt(gageTmp)
	datGageTmp = datGageTmp %>% mutate(Set = dateSel)
	datGage = datGage %>% bind_rows(datGageTmp)

	# Iron Gate
	igTmp = read.rdf(paste0(filePathTmp, 'IronGateReqs.rdf'))
	datIgTmp =  Rdf2dt(igTmp)
	datIgTmp = datIgTmp %>% mutate(Set = dateSel)
	datIg = datIg %>% bind_rows(datIgTmp)

	# Project Supplies
	pjctTmp = read.rdf(paste0(filePathTmp, 'ProjectSupplies.rdf'))
	datPjctTmp =  Rdf2dt(pjctTmp)
	datPjctTmp = datPjctTmp %>% mutate(Set = dateSel)
	datPjct = datPjct %>% bind_rows(datPjctTmp)

	# Inflow
	inflTmp = read.rdf(paste0(filePathTmp, 'Inflow.rdf'))
	datInflTmp =  Rdf2dt(inflTmp)
	datInflTmp = datInflTmp %>% mutate(Set = dateSel)
	datInfl = datInfl %>% bind_rows(datInflTmp)

	# Supply (Forecasts)
	splyTmp = read.rdf(paste0(filePathTmp, 'Supply.rdf'))
	datSplyTmp =  Rdf2dt(splyTmp)
	datSplyTmp = datSplyTmp %>% mutate(Set = dateSel)

	datSply = datSply %>% bind_rows(datSplyTmp)
}



#read NRCS forecast files generated by postprocessWSF.r
#reformat data for EVS
dirNRCS = 'C:/Projects/KlamathRiverBasin/PostProcess/data/output/'
nrcsFiles = c('Willimason_FcastHist_apr-sep_Volumes.csv','Sprague_FcastHist_apr-sep_Volumes.csv','Gerber_FcastHist_apr-sep_Volumes.csv','Clear_FcastHist_apr-sep_Volumes.csv')
nrcsNames = c('Will','Sprag','Gerb','Clear')

ctFiles = length(nrcsFiles)
for(iterFile in 1:ctFiles){
	datFile = fread(paste0(dirNRCS,nrcsFiles[iterFile]))
#	outFile = datFile %>% dplyr::mutate(InitDate = as.Date(InitDate)) %>% dplyr::mutate(date2 = paste0(as.numeric(format(InitDate, '%Y%m%d')),12)) %>% dplyr::mutate(lead = 0) %>% dplyr::select(date2, lead, ValueMax, ValueMin, Value50, Value10, Value90)
	outFile = datFile %>% dplyr::mutate(InitDate = as.Date(InitDate)) %>% dplyr::mutate(date2 = paste0(format(InitDate, '%m/%d/%Y'),' 12')) %>% dplyr::mutate(lead = 0) %>% dplyr::select(date2, lead, ValueMax, ValueMin, Value50, Value10, Value90)
	write.table(outFile,file=paste0(dirEVS,'EVS_flow_ensemble_forecasts_',nrcsNames[iterFile],'.fcst'),row.names=FALSE,col.names=FALSE,quote=F,sep='\t')
#	outFile = datFile %>% dplyr::mutate(InitDate = as.Date(InitDate)) %>% dplyr::mutate(date2 = paste0(as.numeric(format(InitDate, '%Y%m%d')),12)) %>% dplyr::mutate(lead = 0) %>% dplyr::select(date2, lead, ValueMax, ValueMin, Value50, Value10, Value90)
	write.csv(outFile,file=paste0(dirEVS,'EVS_flow_ensemble_forecasts_',nrcsNames[iterFile],'.csv'))
}


	#files in 1000 u/ni/AFts)dd NRCS observed naturalized flow
dirObs = 'C:/Projects/KlamathRiverBasin/PostProcess/data/nrcs/'
obsFiles = c('WMSO3_nrcs_natflow.csv','SPRAG_nrcs_natflow.csv','GERB_nrcs_natflow.csv')
obsNames = c('Will','Sprag','Gerb')

ctFiles = length(obsFiles)
for(iterFile in 1:ctFiles){
	nrcsNatFlow = fread(paste0(dirObs,obsFiles[iterFile]))
	nrcsNatFlowSeas = nrcsNatFlow %>% dplyr::filter(Date %in% c('Apr','May','Jun','Jul','Aug','Sep')) %>%	group_by(Year) %>% summarise(Value_obs=sum(Value)/1000) %>% mutate(Location = 'Williamson R blw Sprague near Chiloquin')
	natflow = nrcsNatFlowSeas %>% left_join(nrcsNatFlow) %>% mutate(mon=match(Date,month.abb)) %>% filter(mon<=4)
	#outFile = natflow %>% dplyr::mutate(date2 = paste0(as.numeric(format(as.Date(paste0(Year,'-',mon,'-',01)), '%Y%m%d')),12)) %>% dplyr::select(date2, Value_obs)
	outFile = natflow %>% dplyr::mutate(date2 = paste0(format(as.Date(paste0(Year,'-',mon,'-',01)), '%m/%d/%Y'),' 12')) %>% dplyr::select(date2, Value_obs)
	write.table(outFile,file=paste0(dirEVS,'EVS_flow_obs_',obsNames[iterFile],'.obs'),row.names=FALSE,col.names=FALSE,quote=F,sep='\t')
	write.csv(outFile,file=paste0(dirEVS,'EVS_flow_obs_',obsNames[iterFile],'.csv'),row.names=FALSE)
	#files in 1000AF units
}
