#===========================================================
# Name: Klamath SRO RiverWare Post-Processing
# Author: D. Broman, USBR Technical Service Center
# Last Modified: 2018-08-02 by MMcGuire
# Description: Reads in RiverWare data files from the Klamath
# River Basin model and calculates performance measures.
#===========================================================
# User Inputs:

#- Working Directory
wd = 'C:/Projects/KlamathRiverBasin/PostProcess/'
#wd = 'C:/Users/MMcguire/Documents/GitHub/Klamath/PostProcess/'

#-Scenario Directory [Location of RiverWare data]
scenDir = 'C:/Projects/KlamathRiverBasin/RiverSmart/Scenario/'

#-Folder Header for Forecast Scenario Runs
scenHdr = 'MRM,RW,Rls,FcstInp'

#-Folder Header for Historical Runs
histHdr = 'MRM,RW,Rls,HistInp'
histDir = 'C:/Projects/KlamathRiverBasin/RiverSmart/Scenario/Historical/trace1'
# All models are run from Jan 1, with historical data appended from
# Jan 1 to start of forecast - forecast start times 1/1, 2/1, 3/1, 4/1, 5/1
#dateList = c('2006-01-01', '2010-01-01')

#- Output Directory
dirOup = 'data/output/'
dirEVS = 'C:/Projects/KlamathRiverBasin/EVS_5.6/Inputs/'

#===========================================================
#-postprocess_lib.r contains custom functions and required R packages
setwd(wd)
source('src/fncnLib.r')

# Read in Data

#read NRCS forecast files generated by postprocessWSF.r
#reformat data for EVS
dirNRCS = 'C:/Projects/KlamathRiverBasin/PostProcess/data/output/'
nrcsFiles = c('Willimason_FcastHist_apr-sep_Volumes.csv','Sprague_FcastHist_apr-sep_Volumes.csv','Gerber_FcastHist_apr-sep_Volumes.csv','Clear_FcastHist_apr-sep_Volumes.csv')
nrcsNames = c('Will','Sprag','Gerb','Clear')
startDates = c('1993-01-01','1993-01-01','2005-01-01','2005-01-01')
endDates = c('2016-04-01','2016-04-01','2016-04-01','2016-04-01')

ctFiles = length(nrcsFiles)
for(iterFile in 1:ctFiles){
	datFile = fread(paste0(dirNRCS,nrcsFiles[iterFile]))
	datFile = datFile %>% dplyr::mutate(InitDate = as.Date(InitDate)) %>% dplyr::filter(InitDate >= startDates[iterFile] & InitDate <= endDates[iterFile])
#	outFile = datFile %>% dplyr::mutate(InitDate = as.Date(InitDate)) %>% dplyr::mutate(date2 = paste0(as.numeric(format(InitDate, '%Y%m%d')),12)) %>% dplyr::mutate(lead = 0) %>% dplyr::select(date2, lead, ValueMax, ValueMin, Value50, Value10, Value90)
	outFile = datFile %>% dplyr::mutate(date2 = paste0(format(InitDate, '%m/%d/%Y'),' 12')) %>% dplyr::mutate(lead = ifelse(month(InitDate)==1,2160,ifelse(month(InitDate)==2,1440,ifelse(month(InitDate)==3,720,ifelse(month(InitDate)==4,0,0))))) %>% dplyr::select(date2, lead, ValueMin, Value10, Value50, Value90, ValueMax)
	write.table(outFile,file=paste0(dirEVS,'EVS_flow_ensemble_forecasts_',nrcsNames[iterFile],'.fcst'),row.names=FALSE,col.names=FALSE,quote=F,sep='\t')
	outFile = outFile %>% dplyr::select(date2, lead, Value50)
	write.table(outFile,file=paste0(dirEVS,'EVS_flow_50percent_',nrcsNames[iterFile],'.fcst'),row.names=FALSE,col.names=FALSE,quote=F,sep='\t')
#	outFile = datFile %>% dplyr::mutate(InitDate = as.Date(InitDate)) %>% dplyr::mutate(date2 = paste0(as.numeric(format(InitDate, '%Y%m%d')),12)) %>% dplyr::mutate(lead = 0) %>% dplyr::select(date2, lead, ValueMax, ValueMin, Value50, Value10, Value90)
#	write.csv(outFile,file=paste0(dirEVS,'EVS_flow_ensemble_forecasts_',nrcsNames[iterFile],'.csv'))
}


	#files in 1000 u/ni/AFts)dd NRCS observed naturalized flow
dirObs = 'C:/Projects/KlamathRiverBasin/PostProcess/data/nrcs/'
obsFiles = c('WMSO3_nrcs_natflow.csv','SPRAG_nrcs_natflow.csv','GERB_nrcs_natflow.csv')
obsNames = c('Will','Sprag','Gerb')
startDates = c('1993-01-01','1993-01-01','2005-01-01')
endDates = c('2016-04-01','2016-04-01','2016-04-01')

ctFiles = length(obsFiles)
for(iterFile in 1:ctFiles){
	nrcsNatFlow = fread(paste0(dirObs,obsFiles[iterFile]))
	nrcsNatFlowSeas = nrcsNatFlow %>% dplyr::filter(Date %in% c('Apr','May','Jun','Jul','Aug','Sep')) %>%	group_by(Year) %>% summarise(Value_obs=sum(Value)/1000) %>% mutate(Location = 'Williamson R blw Sprague near Chiloquin')
	natflow = nrcsNatFlowSeas %>% left_join(nrcsNatFlow) %>% mutate(mon=match(Date,month.abb)) %>% filter(mon<=4)
	natflow = natflow %>% dplyr::mutate(InitDate = as.Date(paste0(Year,'-',mon,'-',01))) %>% dplyr::filter(InitDate >= startDates[iterFile] & InitDate <= endDates[iterFile])
	#outFile = natflow %>% dplyr::mutate(date2 = paste0(as.numeric(format(as.Date(paste0(Year,'-',mon,'-',01)), '%Y%m%d')),12)) %>% dplyr::select(date2, Value_obs)
	outFile = natflow %>% dplyr::mutate(date2 = paste0(format(as.Date(paste0(Year,'-',mon,'-',01)), '%m/%d/%Y'),' 12')) %>% dplyr::select(date2, Value_obs)
	write.table(outFile,file=paste0(dirEVS,'EVS_flow_obs_Apr-Sep',obsNames[iterFile],'.obs'),row.names=FALSE,col.names=FALSE,quote=F,sep='\t')
#	write.csv(outFile,file=paste0(dirEVS,'EVS_flow_obs_',obsNames[iterFile],'.csv'),row.names=FALSE)
	#files in 1000AF units

	nrcsNatFlowSeas = nrcsNatFlow %>% dplyr::filter(Date %in% c('Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov')) %>%	group_by(Year) %>% summarise(Value_obs=sum(Value)/1000) %>% mutate(Location = 'Williamson R blw Sprague near Chiloquin')
	natflow = nrcsNatFlowSeas %>% left_join(nrcsNatFlow) %>% mutate(mon=match(Date,month.abb)) %>% filter(mon<=4)
	natflow = natflow %>% dplyr::mutate(InitDate = as.Date(paste0(Year,'-',mon,'-',01))) %>% dplyr::filter(InitDate >= startDates[iterFile] & InitDate <= endDates[iterFile])
	#outFile = natflow %>% dplyr::mutate(date2 = paste0(as.numeric(format(as.Date(paste0(Year,'-',mon,'-',01)), '%Y%m%d')),12)) %>% dplyr::select(date2, Value_obs)
	outFile = natflow %>% dplyr::mutate(date2 = paste0(format(as.Date(paste0(Year,'-',mon,'-',01)), '%m/%d/%Y'),' 12')) %>% dplyr::select(date2, Value_obs)
	write.table(outFile,file=paste0(dirEVS,'EVS_flow_obs_Mar-Nov',obsNames[iterFile],'.obs'),row.names=FALSE,col.names=FALSE,quote=F,sep='\t')

}
